---- MODULE OneBitMutexNoSymmetryMC ----
EXTENDS OneBitMutex, TLC, TLCExt

\* MV CONSTANT declarations@modelParameterConstants
CONSTANTS
A, B
----

\* MV CONSTANT definitions Procs
const_144491423291817000 == 
{A, B}
----

\* SPECIFICATION definition @modelBehaviorSpec:0
spec_144491423292818000 ==
Spec
----
\* PROPERTY definition @modelCorrectnessProperties:0
prop_144491423293819000 ==
StarvationFreedom
----

PostCondition ==
	/\ TLCSet(42, TLCGet("generated"))
  	/\ \/ CounterExample = [state|->{},action|->{}]
  	   \/ /\ CounterExample = 
				[ action |->
				      { << << 1,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "ncs" @@ B :> "ncs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "ncs",
				             location |->
				                 [ beginLine |-> 56,
				                   beginColumn |-> 14,
				                   endLine |-> 58,
				                   endColumn |-> 51,
				                   module |-> "OneBitMutex" ] ],
				           << 2,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e1" @@ B :> "ncs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >> >>,
				        << << 2,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e1" @@ B :> "ncs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "ncs",
				             location |->
				                 [ beginLine |-> 56,
				                   beginColumn |-> 14,
				                   endLine |-> 58,
				                   endColumn |-> 51,
				                   module |-> "OneBitMutex" ] ],
				           << 3,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e1" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >> >>,
				        << << 3,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e1" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "e1",
				             location |->
				                 [ beginLine |-> 60,
				                   beginColumn |-> 13,
				                   endLine |-> 64,
				                   endColumn |-> 29,
				                   module |-> "OneBitMutex" ] ],
				           << 4,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {A}),
				                other |-> (A :> A @@ B :> A) ] >> >>,
				        << << 4,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {A}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "e2",
				             location |->
				                 [ beginLine |-> 66,
				                   beginColumn |-> 13,
				                   endLine |-> 74,
				                   endColumn |-> 21,
				                   module |-> "OneBitMutex" ] ],
				           << 5,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e3"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >> >>,
				        << << 5,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e3"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "e3",
				             location |->
				                 [ beginLine |-> 76,
				                   beginColumn |-> 13,
				                   endLine |-> 82,
				                   endColumn |-> 50,
				                   module |-> "OneBitMutex" ] ],
				           << 6,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >> >>,
				        << << 6,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "e2",
				             location |->
				                 [ beginLine |-> 66,
				                   beginColumn |-> 13,
				                   endLine |-> 74,
				                   endColumn |-> 21,
				                   module |-> "OneBitMutex" ] ],
				           << 7,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "cs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >> >>,
				        << << 7,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "cs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "e1",
				             location |->
				                 [ beginLine |-> 60,
				                   beginColumn |-> 13,
				                   endLine |-> 64,
				                   endColumn |-> 29,
				                   module |-> "OneBitMutex" ] ],
				           << 8,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e2" @@ B :> "cs"),
				                unchecked |-> (A :> {B} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >> >>,
				        << << 8,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e2" @@ B :> "cs"),
				                unchecked |-> (A :> {B} @@ B :> {}),
				                other |-> (A :> A @@ B :> A) ] >>,
				           [ name |-> "e2",
				             location |->
				                 [ beginLine |-> 66,
				                   beginColumn |-> 13,
				                   endLine |-> 74,
				                   endColumn |-> 21,
				                   module |-> "OneBitMutex" ] ],
				           << 9,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e3" @@ B :> "cs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 9,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e3" @@ B :> "cs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "cs",
				             location |->
				                 [ beginLine |-> 99,
				                   beginColumn |-> 13,
				                   endLine |-> 102,
				                   endColumn |-> 50,
				                   module |-> "OneBitMutex" ] ],
				           << 10,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e3" @@ B :> "f"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 10,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e3" @@ B :> "f"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e3",
				             location |->
				                 [ beginLine |-> 76,
				                   beginColumn |-> 13,
				                   endLine |-> 82,
				                   endColumn |-> 50,
				                   module |-> "OneBitMutex" ] ],
				           << 11,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e4" @@ B :> "f"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 11,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e4" @@ B :> "f"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "f",
				             location |->
				                 [ beginLine |-> 104,
				                   beginColumn |-> 12,
				                   endLine |-> 107,
				                   endColumn |-> 46,
				                   module |-> "OneBitMutex" ] ],
				           << 12,
				              [ x |-> (A :> TRUE @@ B :> FALSE),
				                pc |-> (A :> "e4" @@ B :> "ncs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 12,
				              [ x |-> (A :> TRUE @@ B :> FALSE),
				                pc |-> (A :> "e4" @@ B :> "ncs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "ncs",
				             location |->
				                 [ beginLine |-> 56,
				                   beginColumn |-> 14,
				                   endLine |-> 58,
				                   endColumn |-> 51,
				                   module |-> "OneBitMutex" ] ],
				           << 13,
				              [ x |-> (A :> TRUE @@ B :> FALSE),
				                pc |-> (A :> "e4" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 13,
				              [ x |-> (A :> TRUE @@ B :> FALSE),
				                pc |-> (A :> "e4" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e4",
				             location |->
				                 [ beginLine |-> 84,
				                   beginColumn |-> 13,
				                   endLine |-> 87,
				                   endColumn |-> 47,
				                   module |-> "OneBitMutex" ] ],
				           << 14,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e5" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 14,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e5" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e5",
				             location |->
				                 [ beginLine |-> 89,
				                   beginColumn |-> 13,
				                   endLine |-> 92,
				                   endColumn |-> 50,
				                   module |-> "OneBitMutex" ] ],
				           << 15,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e1" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 15,
				              [ x |-> (A :> FALSE @@ B :> FALSE),
				                pc |-> (A :> "e1" @@ B :> "e1"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e1",
				             location |->
				                 [ beginLine |-> 60,
				                   beginColumn |-> 13,
				                   endLine |-> 64,
				                   endColumn |-> 29,
				                   module |-> "OneBitMutex" ] ],
				           << 16,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {A}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 16,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {A}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e2",
				             location |->
				                 [ beginLine |-> 66,
				                   beginColumn |-> 13,
				                   endLine |-> 74,
				                   endColumn |-> 21,
				                   module |-> "OneBitMutex" ] ],
				           << 17,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e3"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 17,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e3"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e3",
				             location |->
				                 [ beginLine |-> 76,
				                   beginColumn |-> 13,
				                   endLine |-> 82,
				                   endColumn |-> 50,
				                   module |-> "OneBitMutex" ] ],
				           << 18,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 18,
				              [ x |-> (A :> FALSE @@ B :> TRUE),
				                pc |-> (A :> "e1" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e1",
				             location |->
				                 [ beginLine |-> 60,
				                   beginColumn |-> 13,
				                   endLine |-> 64,
				                   endColumn |-> 29,
				                   module |-> "OneBitMutex" ] ],
				           << 19,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e2" @@ B :> "e2"),
				                unchecked |-> (A :> {B} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 19,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e2" @@ B :> "e2"),
				                unchecked |-> (A :> {B} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e2",
				             location |->
				                 [ beginLine |-> 66,
				                   beginColumn |-> 13,
				                   endLine |-> 74,
				                   endColumn |-> 21,
				                   module |-> "OneBitMutex" ] ],
				           << 20,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e3" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >>,
				        << << 20,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e3" @@ B :> "e2"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >>,
				           [ name |-> "e2",
				             location |->
				                 [ beginLine |-> 66,
				                   beginColumn |-> 13,
				                   endLine |-> 74,
				                   endColumn |-> 21,
				                   module |-> "OneBitMutex" ] ],
				           << 9,
				              [ x |-> (A :> TRUE @@ B :> TRUE),
				                pc |-> (A :> "e3" @@ B :> "cs"),
				                unchecked |-> (A :> {} @@ B :> {}),
				                other |-> (A :> B @@ B :> A) ] >> >> },
				  state |->
				      { << 1,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "ncs" @@ B :> "ncs"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 2,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e1" @@ B :> "ncs"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 3,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e1" @@ B :> "e1"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 4,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e1" @@ B :> "e2"),
				             unchecked |-> (A :> {} @@ B :> {A}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 5,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e1" @@ B :> "e3"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 6,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e1" @@ B :> "e2"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 7,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e1" @@ B :> "cs"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 8,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e2" @@ B :> "cs"),
				             unchecked |-> (A :> {B} @@ B :> {}),
				             other |-> (A :> A @@ B :> A) ] >>,
				        << 9,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e3" @@ B :> "cs"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 10,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e3" @@ B :> "f"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 11,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e4" @@ B :> "f"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 12,
				           [ x |-> (A :> TRUE @@ B :> FALSE),
				             pc |-> (A :> "e4" @@ B :> "ncs"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 13,
				           [ x |-> (A :> TRUE @@ B :> FALSE),
				             pc |-> (A :> "e4" @@ B :> "e1"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 14,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e5" @@ B :> "e1"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 15,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e1" @@ B :> "e1"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 16,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e1" @@ B :> "e2"),
				             unchecked |-> (A :> {} @@ B :> {A}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 17,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e1" @@ B :> "e3"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 18,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e1" @@ B :> "e2"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 19,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e2" @@ B :> "e2"),
				             unchecked |-> (A :> {B} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 20,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e3" @@ B :> "e2"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >> } ]
  	      /\ ToTrace(CounterExample) =
						<< [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "ncs" @@ B :> "ncs"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e1" @@ B :> "ncs"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e1" @@ B :> "e1"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e1" @@ B :> "e2"),
						     unchecked |-> (A :> {} @@ B :> {A}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e1" @@ B :> "e3"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e1" @@ B :> "e2"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e1" @@ B :> "cs"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e2" @@ B :> "cs"),
						     unchecked |-> (A :> {B} @@ B :> {}),
						     other |-> (A :> A @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e3" @@ B :> "cs"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e3" @@ B :> "f"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e4" @@ B :> "f"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> FALSE),
						     pc |-> (A :> "e4" @@ B :> "ncs"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> FALSE),
						     pc |-> (A :> "e4" @@ B :> "e1"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e5" @@ B :> "e1"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e1" @@ B :> "e1"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e1" @@ B :> "e2"),
						     unchecked |-> (A :> {} @@ B :> {A}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e1" @@ B :> "e3"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e1" @@ B :> "e2"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e2" @@ B :> "e2"),
						     unchecked |-> (A :> {B} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e3" @@ B :> "e2"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ] >>
  	      /\ ToTrace(CounterExample) = << [ x |-> (A :> FALSE @@ B :> FALSE),
										     pc |-> (A :> "ncs" @@ B :> "ncs"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> FALSE),
										     pc |-> (A :> "e1" @@ B :> "ncs"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> FALSE),
										     pc |-> (A :> "e1" @@ B :> "e1"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> TRUE),
										     pc |-> (A :> "e1" @@ B :> "e2"),
										     unchecked |-> (A :> {} @@ B :> {A}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> TRUE),
										     pc |-> (A :> "e1" @@ B :> "e3"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> TRUE),
										     pc |-> (A :> "e1" @@ B :> "e2"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> TRUE),
										     pc |-> (A :> "e1" @@ B :> "cs"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> TRUE),
										     pc |-> (A :> "e2" @@ B :> "cs"),
										     unchecked |-> (A :> {B} @@ B :> {}),
										     other |-> (A :> A @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> TRUE),
										     pc |-> (A :> "e3" @@ B :> "cs"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> TRUE),
										     pc |-> (A :> "e3" @@ B :> "f"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> TRUE),
										     pc |-> (A :> "e4" @@ B :> "f"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> FALSE),
										     pc |-> (A :> "e4" @@ B :> "ncs"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> FALSE),
										     pc |-> (A :> "e4" @@ B :> "e1"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> FALSE),
										     pc |-> (A :> "e5" @@ B :> "e1"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> FALSE),
										     pc |-> (A :> "e1" @@ B :> "e1"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> TRUE),
										     pc |-> (A :> "e1" @@ B :> "e2"),
										     unchecked |-> (A :> {} @@ B :> {A}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> TRUE),
										     pc |-> (A :> "e1" @@ B :> "e3"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> FALSE @@ B :> TRUE),
										     pc |-> (A :> "e1" @@ B :> "e2"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> TRUE),
										     pc |-> (A :> "e2" @@ B :> "e2"),
										     unchecked |-> (A :> {B} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ],
										   [ x |-> (A :> TRUE @@ B :> TRUE),
										     pc |-> (A :> "e3" @@ B :> "e2"),
										     unchecked |-> (A :> {} @@ B :> {}),
										     other |-> (A :> B @@ B :> A) ] >>
  	      /\ LET J == INSTANCE Json
  	         IN /\ J!JsonSerialize("OneBitMutextNoSymmetry.json", ToTrace(CounterExample))
                /\ PrintT(<<"Dumped trace to json", "OneBitMutextNoSymmetry.json">>)

=============================================================================
