---- MODULE OneBitMutexNoSymmetryMC ----
EXTENDS OneBitMutex, TLC, TLCExt

\* MV CONSTANT declarations@modelParameterConstants
CONSTANTS
A, B
----

\* MV CONSTANT definitions Procs
const_144491423291817000 == 
{A, B}
----

\* SPECIFICATION definition @modelBehaviorSpec:0
spec_144491423292818000 ==
Spec
----
\* PROPERTY definition @modelCorrectnessProperties:0
prop_144491423293819000 ==
StarvationFreedom
----

PostCondition ==
	/\ TLCSet(42, TLCGet("generated"))
  	/\ \/ /\ CounterExample = 
				[ action |->
					{ << << 1,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "ncs" @@ B :> "ncs"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "ncs",
					       context |-> [self |-> A],
					       location |->
					           [ beginLine |-> 56,
					             beginColumn |-> 14,
					             endLine |-> 58,
					             endColumn |-> 51,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 2,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e1" @@ B :> "ncs"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 2,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e1" @@ B :> "ncs"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e1",
					       context |-> [self |-> A],
					       location |->
					           [ beginLine |-> 60,
					             beginColumn |-> 13,
					             endLine |-> 64,
					             endColumn |-> 29,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 3,
					        [ x |-> (A :> TRUE @@ B :> FALSE),
					          pc |-> (A :> "e2" @@ B :> "ncs"),
					          unchecked |-> (A :> {B} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 3,
					        [ x |-> (A :> TRUE @@ B :> FALSE),
					          pc |-> (A :> "e2" @@ B :> "ncs"),
					          unchecked |-> (A :> {B} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "ncs",
					       context |-> [self |-> B],
					       location |->
					           [ beginLine |-> 56,
					             beginColumn |-> 14,
					             endLine |-> 58,
					             endColumn |-> 51,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 4,
					        [ x |-> (A :> TRUE @@ B :> FALSE),
					          pc |-> (A :> "e2" @@ B :> "e1"),
					          unchecked |-> (A :> {B} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 4,
					        [ x |-> (A :> TRUE @@ B :> FALSE),
					          pc |-> (A :> "e2" @@ B :> "e1"),
					          unchecked |-> (A :> {B} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e2",
					       context |-> [self |-> A],
					       location |->
					           [ beginLine |-> 66,
					             beginColumn |-> 13,
					             endLine |-> 74,
					             endColumn |-> 21,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 5,
					        [ x |-> (A :> TRUE @@ B :> FALSE),
					          pc |-> (A :> "e3" @@ B :> "e1"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 5,
					        [ x |-> (A :> TRUE @@ B :> FALSE),
					          pc |-> (A :> "e3" @@ B :> "e1"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e1",
					       context |-> [self |-> B],
					       location |->
					           [ beginLine |-> 60,
					             beginColumn |-> 13,
					             endLine |-> 64,
					             endColumn |-> 29,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 6,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e3" @@ B :> "e2"),
					          unchecked |-> (A :> {} @@ B :> {A}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 6,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e3" @@ B :> "e2"),
					          unchecked |-> (A :> {} @@ B :> {A}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e2",
					       context |-> [self |-> B],
					       location |->
					           [ beginLine |-> 66,
					             beginColumn |-> 13,
					             endLine |-> 74,
					             endColumn |-> 21,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 7,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e3" @@ B :> "e3"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 7,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e3" @@ B :> "e3"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e3",
					       context |-> [self |-> B],
					       location |->
					           [ beginLine |-> 76,
					             beginColumn |-> 13,
					             endLine |-> 82,
					             endColumn |-> 50,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 8,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e3" @@ B :> "e4"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 8,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e3" @@ B :> "e4"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e3",
					       context |-> [self |-> A],
					       location |->
					           [ beginLine |-> 76,
					             beginColumn |-> 13,
					             endLine |-> 82,
					             endColumn |-> 50,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 9,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e4" @@ B :> "e4"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 9,
					        [ x |-> (A :> TRUE @@ B :> TRUE),
					          pc |-> (A :> "e4" @@ B :> "e4"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e4",
					       context |-> [self |-> A],
					       location |->
					           [ beginLine |-> 84,
					             beginColumn |-> 13,
					             endLine |-> 87,
					             endColumn |-> 47,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 10,
					        [ x |-> (A :> FALSE @@ B :> TRUE),
					          pc |-> (A :> "e5" @@ B :> "e4"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 10,
					        [ x |-> (A :> FALSE @@ B :> TRUE),
					          pc |-> (A :> "e5" @@ B :> "e4"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e4",
					       context |-> [self |-> B],
					       location |->
					           [ beginLine |-> 84,
					             beginColumn |-> 13,
					             endLine |-> 87,
					             endColumn |-> 47,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 11,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e5" @@ B :> "e5"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 11,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e5" @@ B :> "e5"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e5",
					       context |-> [self |-> A],
					       location |->
					           [ beginLine |-> 89,
					             beginColumn |-> 13,
					             endLine |-> 92,
					             endColumn |-> 50,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 12,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e1" @@ B :> "e5"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 12,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e1" @@ B :> "e5"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e5",
					       context |-> [self |-> B],
					       location |->
					           [ beginLine |-> 89,
					             beginColumn |-> 13,
					             endLine |-> 92,
					             endColumn |-> 50,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 13,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e1" @@ B :> "e1"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >>,
					  << << 13,
					        [ x |-> (A :> FALSE @@ B :> FALSE),
					          pc |-> (A :> "e1" @@ B :> "e1"),
					          unchecked |-> (A :> {} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >>,
					     [ name |-> "e1",
					       context |-> [self |-> A],
					       location |->
					           [ beginLine |-> 60,
					             beginColumn |-> 13,
					             endLine |-> 64,
					             endColumn |-> 29,
					             module |-> "OneBitMutex" ],
					       parameters |-> <<"self">> ],
					     << 4,
					        [ x |-> (A :> TRUE @@ B :> FALSE),
					          pc |-> (A :> "e2" @@ B :> "e1"),
					          unchecked |-> (A :> {B} @@ B :> {}),
					          other |-> (A :> B @@ B :> A) ] >> >> },
				  state |->
				      { << 1,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "ncs" @@ B :> "ncs"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 2,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e1" @@ B :> "ncs"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 3,
				           [ x |-> (A :> TRUE @@ B :> FALSE),
				             pc |-> (A :> "e2" @@ B :> "ncs"),
				             unchecked |-> (A :> {B} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 4,
				           [ x |-> (A :> TRUE @@ B :> FALSE),
				             pc |-> (A :> "e2" @@ B :> "e1"),
				             unchecked |-> (A :> {B} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 5,
				           [ x |-> (A :> TRUE @@ B :> FALSE),
				             pc |-> (A :> "e3" @@ B :> "e1"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 6,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e3" @@ B :> "e2"),
				             unchecked |-> (A :> {} @@ B :> {A}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 7,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e3" @@ B :> "e3"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 8,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e3" @@ B :> "e4"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 9,
				           [ x |-> (A :> TRUE @@ B :> TRUE),
				             pc |-> (A :> "e4" @@ B :> "e4"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 10,
				           [ x |-> (A :> FALSE @@ B :> TRUE),
				             pc |-> (A :> "e5" @@ B :> "e4"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 11,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e5" @@ B :> "e5"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 12,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e1" @@ B :> "e5"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >>,
				        << 13,
				           [ x |-> (A :> FALSE @@ B :> FALSE),
				             pc |-> (A :> "e1" @@ B :> "e1"),
				             unchecked |-> (A :> {} @@ B :> {}),
				             other |-> (A :> B @@ B :> A) ] >> } ]
  	      /\ ToTrace(CounterExample) =
						<< [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "ncs" @@ B :> "ncs"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e1" @@ B :> "ncs"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> FALSE),
						     pc |-> (A :> "e2" @@ B :> "ncs"),
						     unchecked |-> (A :> {B} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> FALSE),
						     pc |-> (A :> "e2" @@ B :> "e1"),
						     unchecked |-> (A :> {B} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> FALSE),
						     pc |-> (A :> "e3" @@ B :> "e1"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e3" @@ B :> "e2"),
						     unchecked |-> (A :> {} @@ B :> {A}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e3" @@ B :> "e3"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e3" @@ B :> "e4"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> TRUE @@ B :> TRUE),
						     pc |-> (A :> "e4" @@ B :> "e4"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> TRUE),
						     pc |-> (A :> "e5" @@ B :> "e4"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e5" @@ B :> "e5"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e1" @@ B :> "e5"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ],
						   [ x |-> (A :> FALSE @@ B :> FALSE),
						     pc |-> (A :> "e1" @@ B :> "e1"),
						     unchecked |-> (A :> {} @@ B :> {}),
						     other |-> (A :> B @@ B :> A) ] >>

=============================================================================
