/*******************************************************************************
 * Copyright (c) 2026 NVIDIA Corp. All rights reserved.
 *
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Contributors:
 *   Markus Alexander Kuppe - initial implementation
 ******************************************************************************/
package tlc2.mcp;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import tlc2.TLC;

/**
 * MCP tool for loading and replaying TLC trace files.
 * 
 * Loads previously generated trace files and replays them, allowing for custom
 * ALIAS expressions to format and analyze the trace.
 */
public class TLCTraceTool implements MCPTool {

	@Override
	public String getDescription() {
		return "Load and replay a previously generated TLC trace file. This tool is particularly useful "
				+ "after tlaplus_mcp_tlc_check finds a counterexample and automatically generates a trace file. "
				+ "Trace files are .tlc files with the naming pattern: "
				+ "{specName}_trace_T{timestamp}_F{fp}_W{workers}_M{mode}.tlc. By rerunning TLC with -loadtrace, "
				+ "you can add or modify ALIAS expressions in the configuration file to derive compound values, "
				+ "rename variables, filter out variables, or create custom animations of the trace for better "
				+ "analysis. The ALIAS feature allows you to evaluate expressions on pairs of states (s -> t) in "
				+ "the error trace and display custom formatted output instead of raw state dumps.";
	}

	@Override
	public JsonObject getInputSchema() {
		JsonObject schema = new JsonObject();
		schema.addProperty("type", "object");

		JsonObject properties = new JsonObject();

		JsonObject fileName = new JsonObject();
		fileName.addProperty("type", "string");
		fileName.addProperty("description", "The full path to the file containing the TLA+ module.");
		properties.add("fileName", fileName);

		JsonObject traceFile = new JsonObject();
		traceFile.addProperty("type", "string");
		traceFile.addProperty("description",
				"The full path to the trace file to load. This is a .tlc file automatically generated by TLC "
						+ "during model checking (e.g., " + "MySpec_trace_T2024-01-15_10-30-45_F42_W1_Mbfs.tlc).");
		properties.add("traceFile", traceFile);

		JsonObject cfgFile = new JsonObject();
		cfgFile.addProperty("type", "string");
		cfgFile.addProperty("description",
				"Optional path to a custom TLC configuration file. This is where you would add or modify "
						+ "ALIAS expressions for trace analysis.");
		properties.add("cfgFile", cfgFile);

		JsonObject extraOpts = new JsonObject();
		extraOpts.addProperty("type", "array");
		JsonObject extraOptsItems = new JsonObject();
		extraOptsItems.addProperty("type", "string");
		extraOpts.add("items", extraOptsItems);
		extraOpts.addProperty("description",
				"Optional array of additional command-line options to pass to TLC beyond [-loadtrace].");
		properties.add("extraOpts", extraOpts);

		JsonObject extraJavaOpts = new JsonObject();
		extraJavaOpts.addProperty("type", "array");
		JsonObject extraJavaOptsItems = new JsonObject();
		extraJavaOptsItems.addProperty("type", "string");
		extraJavaOpts.add("items", extraJavaOptsItems);
		extraJavaOpts.addProperty("description",
				"Optional array of additional Java options to pass to the JVM (e.g., [\"-Xmx4g\"]).");
		properties.add("extraJavaOpts", extraJavaOpts);

		schema.add("properties", properties);

		JsonArray required = new JsonArray();
		required.add("fileName");
		required.add("traceFile");
		schema.add("required", required);

		return schema;
	}

	/**
	 * Extract fingerprint index from trace filename. Format:
	 * {specName}_trace_T{timestamp}_F{fp}_W{workers}_M{mode}.tlc
	 */
	private Integer extractFingerprintFromTrace(String traceFilePath) {
		String filename = new File(traceFilePath).getName();
		Pattern pattern = Pattern.compile("_F(\\d+)_");
		Matcher matcher = pattern.matcher(filename);
		if (matcher.find()) {
			return Integer.parseInt(matcher.group(1));
		}
		return null;
	}

	@Override
	public JsonObject execute(JsonObject arguments) throws Exception {
		if (!arguments.has("fileName")) {
			throw new IllegalArgumentException("Missing required argument: fileName");
		}

		if (!arguments.has("traceFile")) {
			throw new IllegalArgumentException("Missing required argument: traceFile");
		}

		String fileName = arguments.get("fileName").getAsString();
		String traceFile = arguments.get("traceFile").getAsString();

		// Check if files exist
		File file = new File(fileName);
		if (!file.exists()) {
			JsonObject result = new JsonObject();
			JsonArray content = new JsonArray();
			JsonObject contentItem = new JsonObject();
			contentItem.addProperty("type", "text");
			contentItem.addProperty("text", "File " + fileName + " does not exist on disk.");
			content.add(contentItem);
			result.add("content", content);
			return result;
		}

		File trace = new File(traceFile);
		if (!trace.exists()) {
			JsonObject result = new JsonObject();
			JsonArray content = new JsonArray();
			JsonObject contentItem = new JsonObject();
			contentItem.addProperty("type", "text");
			contentItem.addProperty("text", "Trace file " + traceFile + " does not exist on disk.");
			content.add(contentItem);
			result.add("content", content);
			return result;
		}

		// Extract fingerprint from trace filename
		Integer fpValue = extractFingerprintFromTrace(traceFile);

		// Build TLC arguments
		List<String> tlcArgs = new ArrayList<>();
		tlcArgs.add("-cleanup");

		// Add fingerprint option if available
		if (fpValue != null) {
			tlcArgs.add("-fp");
			tlcArgs.add(String.valueOf(fpValue));
		}

		// Add loadtrace options
		tlcArgs.add("-loadtrace");
		tlcArgs.add("tlc");
		tlcArgs.add(traceFile);

		// Add extra options
		if (arguments.has("extraOpts")) {
			JsonArray extraOpts = arguments.getAsJsonArray("extraOpts");
			for (JsonElement opt : extraOpts) {
				tlcArgs.add(opt.getAsString());
			}
		}

		// Add config file if provided
		if (arguments.has("cfgFile")) {
			String cfgFile = arguments.get("cfgFile").getAsString();
			tlcArgs.add("-config");
			tlcArgs.add(cfgFile);
		}

		// Add the spec file
		tlcArgs.add(fileName);

		// Apply Java options if provided
		if (arguments.has("extraJavaOpts")) {
			JsonArray extraJavaOpts = arguments.getAsJsonArray("extraJavaOpts");
			for (JsonElement opt : extraJavaOpts) {
				String optStr = opt.getAsString();
				if (optStr.startsWith("-D")) {
					String[] parts = optStr.substring(2).split("=", 2);
					if (parts.length == 2) {
						System.setProperty(parts[0], parts[1]);
					}
				}
			}
		}

		// Capture output
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		PrintStream ps = new PrintStream(baos);
		PrintStream oldOut = System.out;
		PrintStream oldErr = System.err;

		try {
			System.setOut(ps);
			System.setErr(ps);

			// Run TLC
			TLC tlc = new TLC();
			if (!tlc.handleParameters(tlcArgs.toArray(new String[0]))) {
				throw new Exception("Failed to parse TLC parameters");
			}

			int exitCode = tlc.process();

			ps.flush();
			String output = baos.toString();

			JsonObject result = new JsonObject();
			JsonArray content = new JsonArray();
			JsonObject contentItem = new JsonObject();
			contentItem.addProperty("type", "text");
			contentItem.addProperty("text", "TLC trace replay completed with exit code " + exitCode + ":\n\n" + output);
			content.add(contentItem);
			result.add("content", content);
			return result;

		} finally {
			System.setOut(oldOut);
			System.setErr(oldErr);
			ps.close();
		}
	}
}
