---------------------- MODULE DiskStateQueueEvents -------------------------
EXTENDS DiskStateQueue

\* Instrumentation-only boundaries are explicit stutters or phase changes.
\* Shared-state changes are defined exclusively in DiskStateQueue.
Observe(p, a) ==
    CASE a = "SEnqueueBegin" -> Call(p, "put")
      [] a = "SDequeueBegin" -> Call(p, "get")
      [] a = "SPeekBegin" -> Call(p, "peek")
      [] a \in {"SEnqueueEnd", "SDequeueEnd", "SPeekEnd"} -> Return(p)
      [] a = "Enq" -> AppendEntry(p)
      [] a = "Enqueue" -> Advance(p, "unsafeEnd", "idle")
      [] a = "Deq" -> Remove(p, FALSE)
      [] a = "Peek" -> Remove(p, TRUE)
      [] a \in {"AvailFinished", "AvailWokeFinished"} -> EmptyReturn(p, TRUE)
      [] a = "AvailNoWork" -> EmptyReturn(p, FALSE)
      [] a = "AvailCountLast" -> CountLast(p)
      [] a = "AvailAllWaiting" -> AnnounceLast(p)
      [] a = "AvailWait" -> WaitWorker(p)
      [] a = "AvailWoke" -> WakeWorker(p)
      [] a = "SEnqueueNotify" -> NotifyWorkers(p)
      [] a = "SpillBegin" -> StartOffer(p)
      [] a = "WriterDoWorkBegin" -> EnterWriter(p, TRUE)
      [] a = "WriterDoWorkLate" -> FlushOld(p)
      [] a = "WriterDoWorkEnd" -> Offer(p)
      [] a = "SpillEnd" -> Advance(p, "offered", IF op[p] = "unsafePut" THEN "idle" ELSE "call")
      [] a = "AwaitWriteBegin" -> StartAwait(p)
      [] a = "WriterAwaitBegin" -> EnterWriter(p, FALSE)
      [] a = "WriterAwaitWait" -> WaitWriter(p)
      [] a = "WriterAwaitWoke" -> WakeWriterCaller(p)
      [] a = "WriterAwaitEnd" -> AwaitDone(p)
      [] a = "AwaitWriteEnd" -> pc[p] = "fillReady" /\ UNCHANGED vars
      [] a = "LoadPoolBegin" -> StartTake(p, "load")
      [] a = "TakeCacheBegin" -> StartTake(p, "cache")
      [] a \in {"ReaderDoWorkBegin", "ReaderGetCacheBegin"} -> EnterReader(p)
      [] a \in {"ReaderDoWorkPrefetched", "ReaderGetCachePrefetched"} -> Take(p, "cache")
      [] a \in {"ReaderDoWorkPending", "ReaderGetCacheRead"} -> Take(p, "file")
      [] a = "ReaderDoWorkDirect" -> Take(p, "direct")
      [] a = "ReaderGetCacheEmpty" -> Take(p, "empty")
      [] a = "LoadPoolEnd" -> kind[p] = "loadDone" /\ Advance(p, "filled", "filledReturn")
      [] a = "TakeCacheHit" -> kind[p] = "cacheHit" /\ Advance(p, "filled", "filledReturn")
      [] a = "TakeCacheMiss" -> kind[p] = "cacheMiss" /\ Advance(p, "filled", "filledReturn")
      [] a = "WriterRunBegin" -> p = Writer /\ Boot(p, "w")
      [] a = "ReaderRunBegin" -> p = Reader /\ Boot(p, "r")
      [] a = "WriterWait" -> p = Writer /\ BackgroundWait(p, "w")
      [] a = "ReaderWait" -> p = Reader /\ BackgroundWait(p, "r")
      [] a = "WriterWoke" -> p = Writer /\ BackgroundWake(p, "w")
      [] a = "ReaderWoke" -> p = Reader /\ BackgroundWake(p, "r")
      [] a = "ReaderWakeup" -> p = Writer /\ Publish
      [] a = "WriterWrote" -> p = Writer /\ Advance(p, "published", "run")
      [] a = "ReaderRead" -> p = Reader /\ Prefetch
      [] a = "WriterExit" -> p = Writer /\ BackgroundExit(p, "w")
      [] a = "ReaderExit" -> p = Reader /\ BackgroundExit(p, "r")
      [] a = "NotifyCleaner" -> RequestClean(p)
      [] a = "Clean" -> p = Cleaner /\ Clean
      [] a = "CleanerExit" -> p = Cleaner /\ CleanerExit
      [] a = "FinishAllBegin" -> FinishBegin(p)
      [] a = "FinishAllNotify" -> FinishSignal(p)
      [] a = "FinishAllNotifyMu" -> FinishNotify(p)
      [] a = "FinishAllEnd" -> FinishQueue(p)
      [] a = "FinishWriter" -> FinishWriter(p)
      [] a = "ReaderSetFinished" -> FinishReaderBegin(p)
      [] a = "FinishReader" -> FinishReader(p)
      [] a = "FinishCleaner" -> FinishCleaner(p)
      [] a = "SuspendBegin" -> SuspendBegin(p)
      [] a = "SuspendStop" -> StopWorkers(p)
      [] a = "SuspendAwaitBegin" -> EnterBarrier(p)
      [] a = "SuspendWait" -> WaitBarrier(p)
      [] a = "SuspendWoke" -> WakeBarrier(p)
      [] a = "SuspendRecheck" -> Recheck(p)
      [] a = "SuspendEnd" -> Suspended(p)
      [] a = "SuspendFinished" -> SuspendFinished(p, "queue")
      [] a = "SuspendFinishedOnMu" -> SuspendFinished(p, "mu")
      [] a = "SuspendFinishedOnRecheck" -> SuspendFinished(p, "recheck")
      [] a = "Resume" -> Resume(p)
      [] a = "StartChkpt" -> StartCheckpoint(p)
      [] a = "BeginChkpt" -> Snapshot(p)
      [] a = "CommitChkpt" -> Commit(p)
      [] a = "ReaderRestart" -> Restore(p)
      [] a = "Recover" -> Advance(p, "recovered", "idle")
      [] OTHER -> FALSE
=============================================================================
