#!/bin/sh

## Fix permissions of executables
chmod 755 /opt/TLA+Toolbox/toolbox
chmod 755 /opt/TLA+Toolbox/plugins/org.lamport.openjdk.linux.x86_64_*/jre/bin/*

## Update mime database for x-tla type.
/usr/bin/update-mime-database /usr/share/mime

#- Apt repo
#-- Jenkins Plugin
#-- https://github.com/theoweiss/apt-repo
