/* Generated By:51&JavaCC: Do not edit this line. TLAplusParserConstants.java */
package tla2sany.parser;

public interface TLAplusParserConstants {

  int EOF = 0;
  int BEGIN_MODULE = 1;
  int BEGIN_PRAGMA = 2;
  int _BM1 = 3;
  int CASE0 = 5;
  int CASE1 = 6;
  int CASE1b = 7;
  int CASE1c = 8;
  int CASE2 = 9;
  int CASE2b = 10;
  int CASE2c = 11;
  int CASE3 = 12;
  int CASE6 = 13;
  int CASE6b = 14;
  int CASE6c = 15;
  int CASEN = 16;
  int LETTER = 17;
  int DIGIT = 18;
  int NUMBER = 19;
  int _BM2 = 20;
  int _BM0 = 34;
  int SEPARATOR = 35;
  int END_MODULE = 36;
  int ACTION = 37;
  int ASSUME = 38;
  int ASSUMPTION = 39;
  int CASE = 40;
  int CHOOSE = 41;
  int CONSTANT = 42;
  int ELSE = 43;
  int EXCEPT = 44;
  int EXISTS = 45;
  int EXTENDS = 46;
  int FORALL = 47;
  int IF = 48;
  int INSTANCE = 49;
  int LET = 50;
  int LETIN = 51;
  int LOCAL = 52;
  int MODULE = 53;
  int NEW = 54;
  int OTHER = 55;
  int PROPOSITION = 56;
  int SF = 57;
  int T_EXISTS = 58;
  int T_FORALL = 59;
  int THEN = 60;
  int BY = 61;
  int DEFINE = 62;
  int DF = 63;
  int THEOREM = 64;
  int USE = 65;
  int HIDE = 66;
  int HAVE = 67;
  int OBVIOUS = 68;
  int OMITTED = 69;
  int LAMBDA = 70;
  int TAKE = 71;
  int PROOF = 72;
  int PROVE = 73;
  int QED = 74;
  int RECURSIVE = 75;
  int STATE = 76;
  int TEMPORAL = 77;
  int PICK = 78;
  int WITNESS = 79;
  int SUFFICES = 80;
  int VARIABLE = 81;
  int WF = 82;
  int WITH = 83;
  int COMMA = 84;
  int COLON = 85;
  int COLONCOLON = 86;
  int DOT = 87;
  int US = 88;
  int DEF = 89;
  int LBR = 90;
  int RBR = 91;
  int DEFBREAK = 92;
  int LSB = 93;
  int ARSB = 94;
  int RSB = 95;
  int LWB = 96;
  int RWB = 97;
  int LBC = 98;
  int RBC = 99;
  int LAB = 100;
  int ARAB = 101;
  int RAB = 102;
  int BANG = 103;
  int ARROW = 104;
  int SUBSTITUTE = 105;
  int MAPTO = 106;
  int NUMBER_LITERAL = 107;
  int STRING_LITERAL = 108;
  int BAND = 109;
  int BOR = 110;
  int op_57 = 111;
  int op_68 = 112;
  int op_69 = 113;
  int op_70 = 114;
  int op_76 = 115;
  int op_26 = 116;
  int op_29 = 117;
  int op_58 = 118;
  int CASESEP = 119;
  int op_61 = 120;
  int op_112 = 121;
  int op_113 = 122;
  int op_114 = 123;
  int op_115 = 124;
  int op_116 = 125;
  int op_1 = 126;
  int AND = 127;
  int op_3 = 128;
  int op_4 = 129;
  int OR = 130;
  int op_6 = 131;
  int op_7 = 132;
  int op_8 = 133;
  int op_9 = 134;
  int op_10 = 135;
  int op_11 = 136;
  int op_12 = 137;
  int op_13 = 138;
  int op_14 = 139;
  int op_15 = 140;
  int op_16 = 141;
  int op_17 = 142;
  int op_18 = 143;
  int op_19 = 144;
  int IN = 145;
  int op_21 = 146;
  int op_22 = 147;
  int op_23 = 148;
  int op_24 = 149;
  int op_25 = 150;
  int op_27 = 151;
  int op_30 = 152;
  int op_31 = 153;
  int op_32 = 154;
  int op_33 = 155;
  int op_34 = 156;
  int op_35 = 157;
  int op_36 = 158;
  int op_37 = 159;
  int op_38 = 160;
  int op_39 = 161;
  int op_40 = 162;
  int op_41 = 163;
  int op_42 = 164;
  int op_43 = 165;
  int op_44 = 166;
  int op_45 = 167;
  int op_46 = 168;
  int op_47 = 169;
  int op_48 = 170;
  int op_49 = 171;
  int op_50 = 172;
  int op_51 = 173;
  int op_52 = 174;
  int op_53 = 175;
  int op_54 = 176;
  int op_55 = 177;
  int op_56 = 178;
  int op_59 = 179;
  int op_62 = 180;
  int op_63 = 181;
  int op_64 = 182;
  int EQUALS = 183;
  int op_66 = 184;
  int op_67 = 185;
  int op_71 = 186;
  int op_72 = 187;
  int op_73 = 188;
  int op_74 = 189;
  int op_75 = 190;
  int op_77 = 191;
  int op_78 = 192;
  int op_79 = 193;
  int op_80 = 194;
  int op_81 = 195;
  int op_82 = 196;
  int op_83 = 197;
  int op_84 = 198;
  int op_85 = 199;
  int op_86 = 200;
  int op_87 = 201;
  int op_88 = 202;
  int op_89 = 203;
  int op_90 = 204;
  int op_91 = 205;
  int op_92 = 206;
  int op_93 = 207;
  int op_94 = 208;
  int op_95 = 209;
  int op_96 = 210;
  int op_97 = 211;
  int op_98 = 212;
  int op_100 = 213;
  int op_101 = 214;
  int op_102 = 215;
  int op_103 = 216;
  int op_104 = 217;
  int op_105 = 218;
  int op_106 = 219;
  int op_107 = 220;
  int op_108 = 221;
  int op_109 = 222;
  int op_110 = 223;
  int op_111 = 224;
  int op_117 = 225;
  int op_118 = 226;
  int op_119 = 227;
  int IDENTIFIER = 228;
  int ProofLevelLexeme = 229;
  int ProofImplicitLevelLexeme = 230;
  int ProofStepLexeme = 231;
  int ProofImplicitStepLexeme = 232;
  int ProofStepDotLexeme = 233;
  int BareLevelLexeme = 234;
  int UnnumberedStepLexeme = 235;

  int DEFAULT = 0;
  int PRAGMA = 1;
  int SPEC = 2;
  int IN_COMMENT = 3;
  int EMBEDDED = 4;
  int IN_EOL_COMMENT = 5;

  String[] tokenImage = {
    "<EOF>",
    "<BEGIN_MODULE>",
    "\"--->\"",
    "<_BM1>",
    "<token of kind 4>",
    "<CASE0>",
    "<CASE1>",
    "<CASE1b>",
    "<CASE1c>",
    "<CASE2>",
    "<CASE2b>",
    "<CASE2c>",
    "<CASE3>",
    "<CASE6>",
    "<CASE6b>",
    "<CASE6c>",
    "<CASEN>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<_BM2>",
    "<token of kind 21>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 26>",
    "\"\\\\*\"",
    "<token of kind 28>",
    "\"*)\"",
    "\"*)\"",
    "<token of kind 31>",
    "<token of kind 32>",
    "<token of kind 33>",
    "<_BM0>",
    "<SEPARATOR>",
    "<END_MODULE>",
    "<ACTION>",
    "\"ASSUME\"",
    "<ASSUMPTION>",
    "\"CASE\"",
    "\"CHOOSE\"",
    "<CONSTANT>",
    "\"ELSE\"",
    "\"EXCEPT\"",
    "<EXISTS>",
    "\"EXTENDS\"",
    "<FORALL>",
    "\"IF\"",
    "\"INSTANCE\"",
    "\"LET\"",
    "\"IN\"",
    "\"LOCAL\"",
    "\"MODULE\"",
    "\"NEW\"",
    "\"OTHER\"",
    "<PROPOSITION>",
    "\"SF_\"",
    "\"\\\\EE\"",
    "\"\\\\AA\"",
    "\"THEN\"",
    "\"BY\"",
    "\"DEFINE\"",
    "<DF>",
    "\"THEOREM\"",
    "\"USE\"",
    "\"HIDE\"",
    "\"HAVE\"",
    "\"OBVIOUS\"",
    "\"OMITTED\"",
    "\"LAMBDA\"",
    "\"TAKE\"",
    "\"PROOF\"",
    "\"PROVE\"",
    "\"QED\"",
    "\"RECURSIVE\"",
    "\"STATE\"",
    "<TEMPORAL>",
    "\"PICK\"",
    "\"WITNESS\"",
    "\"SUFFICES\"",
    "<VARIABLE>",
    "\"WF_\"",
    "\"WITH\"",
    "\",\"",
    "\":\"",
    "\"::\"",
    "\".\"",
    "\"_\"",
    "\"==\"",
    "\"(\"",
    "\")\"",
    "\"-|-\"",
    "\"[\"",
    "\"]_\"",
    "\"]\"",
    "\"{|\"",
    "\"|}\"",
    "\"{\"",
    "\"}\"",
    "\"<<\"",
    "\">>_\"",
    "\">>\"",
    "\"!\"",
    "\"->\"",
    "\"<-\"",
    "\"|->\"",
    "<NUMBER_LITERAL>",
    "<STRING_LITERAL>",
    "<BAND>",
    "<BOR>",
    "\"\\\'\"",
    "\"^+\"",
    "\"^*\"",
    "\"^#\"",
    "\"-.\"",
    "\"\\\\lnot\"",
    "\"\\\\neg\"",
    "\"~\"",
    "\"[]\"",
    "\"<>\"",
    "\"ENABLED\"",
    "\"UNCHANGED\"",
    "\"SUBSET\"",
    "\"UNION\"",
    "\"DOMAIN\"",
    "\"//\"",
    "\"/\\\\\"",
    "\"/=\"",
    "\"/\"",
    "\"\\\\/\"",
    "\"\\\\approx\"",
    "\"\\\\asymp\"",
    "\"\\\\bigcirc\"",
    "\"\\\\bullet\"",
    "\"\\\\cap\"",
    "\"\\\\cdot\"",
    "\"\\\\circ\"",
    "\"\\\\cong\"",
    "\"\\\\cup\"",
    "\"\\\\div\"",
    "\"\\\\doteq\"",
    "\"\\\\equiv\"",
    "\"\\\\geq\"",
    "\"\\\\gg\"",
    "\"\\\\in\"",
    "\"\\\\intersect\"",
    "\"\\\\union\"",
    "\"\\\\land\"",
    "\"\\\\leq\"",
    "\"\\\\ll\"",
    "\"\\\\lor\"",
    "\"\\\\o\"",
    "\"\\\\odot\"",
    "\"\\\\ominus\"",
    "\"\\\\oplus\"",
    "\"\\\\oslash\"",
    "\"\\\\otimes\"",
    "\"\\\\prec\"",
    "\"\\\\preceq\"",
    "\"\\\\propto\"",
    "\"\\\\sim\"",
    "\"\\\\simeq\"",
    "\"\\\\sqcap\"",
    "\"\\\\sqcup\"",
    "\"\\\\sqsubset\"",
    "\"\\\\sqsupset\"",
    "\"\\\\sqsubseteq\"",
    "\"\\\\sqsupseteq\"",
    "\"\\\\star\"",
    "\"\\\\subset\"",
    "\"\\\\subseteq\"",
    "\"\\\\succ\"",
    "\"\\\\succeq\"",
    "\"\\\\supset\"",
    "\"\\\\supseteq\"",
    "\"\\\\uplus\"",
    "\"\\\\wr\"",
    "\"\\\\\"",
    "\"~>\"",
    "\"=>\"",
    "\"=<\"",
    "\"=|\"",
    "\"=\"",
    "\"##\"",
    "\"#\"",
    "\"^^\"",
    "\"^\"",
    "\"--\"",
    "\"-|\"",
    "\"-+->\"",
    "\"-\"",
    "\"**\"",
    "\"*\"",
    "\"++\"",
    "\"+\"",
    "\"<=>\"",
    "\"<:\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"...\"",
    "\"..\"",
    "\"||\"",
    "\"|\"",
    "\"|-\"",
    "\"|=\"",
    "\"&&\"",
    "\"&\"",
    "\"$$\"",
    "\"$\"",
    "\"??\"",
    "\"%%\"",
    "\"%\"",
    "\"@@\"",
    "\"!!\"",
    "\":>\"",
    "\":=\"",
    "\"::=\"",
    "\"(+)\"",
    "\"(-)\"",
    "\"(.)\"",
    "\"(/)\"",
    "\"(\\\\X)\"",
    "\"\\\\notin\"",
    "\"\\\\times\"",
    "\"\\\\X\"",
    "<IDENTIFIER>",
    "<ProofLevelLexeme>",
    "<ProofImplicitLevelLexeme>",
    "<ProofStepLexeme>",
    "<ProofImplicitStepLexeme>",
    "<ProofStepDotLexeme>",
    "<BareLevelLexeme>",
    "<UnnumberedStepLexeme>",
  };

}
