// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package tlc2.tool.distributed;


/**
 * 
 * @deprecated not used currently
 * @version $Id$
 */
public final class TLCWorker_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void exit()"),
	new java.rmi.server.Operation("java.lang.Object getNextStates(tlc2.tool.TLCState[])[]")
    };
    
    private static final long interfaceHash = -7211739593295767913L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (opnum < 0) {
	    if (hash == -6307240473358936408L) {
		opnum = 0;
	    } else if (hash == 1512474148561500310L) {
		opnum = 1;
	    } else {
		throw new java.rmi.UnmarshalException("invalid method hash");
	    }
	} else {
	    if (hash != interfaceHash)
		throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	}
	
	tlc2.tool.distributed.TLCWorker server = (tlc2.tool.distributed.TLCWorker) obj;
	switch (opnum) {
	case 0: // exit()
	{
	    call.releaseInputStream();
	    server.exit();
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // getNextStates(TLCState[])
	{
	    tlc2.tool.TLCState[] $param_arrayOf_TLCState_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_arrayOf_TLCState_1 = (tlc2.tool.TLCState[]) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    java.lang.Object[] $result = server.getNextStates($param_arrayOf_TLCState_1);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
