--------------------------- MODULE MCYoYoNoPruning ---------------------------
EXTENDS Integers, TLC, TLCExt

Nodes == 1 .. 5
Edges == {{1,2}, {1,5}, {3,4}, {3,5}, {4,5}}

(*
Nodes == {2,3,4,5,7,11,12,14,20,31,41}
Edges == {{2,31}, {3,11}, {3,12}, {3,14}, {4,14}, {4,20}, 
          {5,11}, {5,12}, {5,20}, {7,20}, {7,31}, 
          {11,12}, {12,20}, {20,41}}
*)

VARIABLES phase, incoming, outgoing, mailbox

INSTANCE YoYoNoPruning

AllPermanentlyDown == <>[](\A n \in Nodes : phase[n] = "down")

PostCondition ==
	CounterExample =
	 [ action |->
      { << << 1,
              [ phase |-> <<"down", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |-> <<{}, {}, {}, {}, {}>> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 2,
              [ phase |-> <<"down", "down", "up", "down", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]} >> ] >> >>,
        << << 2,
              [ phase |-> <<"down", "down", "up", "down", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 3,
              [ phase |-> <<"down", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >> >>,
        << << 3,
              [ phase |-> <<"down", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 4,
              [ phase |-> <<"up", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >> >>,
        << << 4,
              [ phase |-> <<"up", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 5,
              [ phase |-> <<"up", "up", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >> >>,
        << << 5,
              [ phase |-> <<"up", "up", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 6,
              [ phase |-> <<"up", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >> >>,
        << << 6,
              [ phase |-> <<"up", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 7,
              [ phase |-> <<"up", "down", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >> >>,
        << << 7,
              [ phase |-> <<"up", "down", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 3, sndr |-> 3]},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 8,
              [ phase |-> <<"up", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       {[phase |-> "up", sndr |-> 5, reply |-> "no"]},
                       { [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "up", sndr |-> 5, reply |-> "no"] },
                       {} >> ] >> >>,
        << << 8,
              [ phase |-> <<"up", "down", "up", "up", "down">>,
                incoming |-> <<{}, {1}, {}, {3}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       {[phase |-> "up", sndr |-> 5, reply |-> "no"]},
                       { [phase |-> "down", val |-> 3, sndr |-> 3],
                         [phase |-> "up", sndr |-> 5, reply |-> "no"] },
                       {} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 9,
              [ phase |-> <<"up", "down", "up", "down", "down">>,
                incoming |-> <<{}, {1}, {}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {3}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       { [phase |-> "up", sndr |-> 4, reply |-> "no"],
                         [phase |-> "up", sndr |-> 5, reply |-> "no"] },
                       {},
                       {} >> ] >> >>,
        << << 9,
              [ phase |-> <<"up", "down", "up", "down", "down">>,
                incoming |-> <<{}, {1}, {}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {4, 5}, {3}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       { [phase |-> "up", sndr |-> 4, reply |-> "no"],
                         [phase |-> "up", sndr |-> 5, reply |-> "no"] },
                       {},
                       {} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 10,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       {},
                       {},
                       {} >> ] >> >>,
        << << 10,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       {},
                       {},
                       {} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 11,
              [ phase |-> <<"down", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |-> <<{}, {}, {}, {}, {}>> ] >> >>,
        << << 11,
              [ phase |-> <<"down", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |-> <<{}, {}, {}, {}, {}>> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 12,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 12,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 13,
              [ phase |-> <<"up", "down", "down", "down", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 13,
              [ phase |-> <<"up", "down", "down", "down", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 14,
              [ phase |-> <<"up", "down", "down", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 14,
              [ phase |-> <<"up", "down", "down", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 15,
              [ phase |-> <<"up", "down", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 15,
              [ phase |-> <<"up", "down", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 16,
              [ phase |-> <<"up", "up", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 16,
              [ phase |-> <<"up", "up", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 17,
              [ phase |-> <<"up", "down", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 17,
              [ phase |-> <<"up", "down", "up", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 18,
              [ phase |-> <<"up", "down", "down", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       { [phase |-> "down", val |-> 1, sndr |-> 5],
                         [phase |-> "up", sndr |-> 3, reply |-> "yes"] },
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [ phase |-> "up",
                           sndr |-> 3,
                           reply |-> "yes" ] } >> ] >> >>,
        << << 18,
              [ phase |-> <<"up", "down", "down", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       { [phase |-> "down", val |-> 1, sndr |-> 5],
                         [phase |-> "up", sndr |-> 3, reply |-> "yes"] },
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [ phase |-> "up",
                           sndr |-> 3,
                           reply |-> "yes" ] } >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 19,
              [ phase |-> <<"up", "down", "down", "down", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       {},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "up", sndr |-> 3, reply |-> "yes"],
                         [ phase |-> "up",
                           sndr |-> 4,
                           reply |-> "yes" ] } >> ] >> >>,
        << << 19,
              [ phase |-> <<"up", "down", "down", "down", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                       {},
                       {},
                       {},
                       { [phase |-> "down", val |-> 1, sndr |-> 1],
                         [phase |-> "up", sndr |-> 3, reply |-> "yes"],
                         [ phase |-> "up",
                           sndr |-> 4,
                           reply |-> "yes" ] } >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 20,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       {},
                       {},
                       {} >> ] >> >>,
        << << 20,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                         [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                       {},
                       {},
                       {},
                       {} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 21,
              [ phase |-> <<"down", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |-> <<{}, {}, {}, {}, {}>> ] >> >>,
        << << 21,
              [ phase |-> <<"down", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |-> <<{}, {}, {}, {}, {}>> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 22,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 22,
              [ phase |-> <<"up", "down", "down", "down", "down">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {},
                       {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 23,
              [ phase |-> <<"up", "down", "down", "down", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >>,
        << << 23,
              [ phase |-> <<"up", "down", "down", "down", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
           [ name |-> "UnnamedAction",
             location |->
                 [ beginLine |-> 16,
                   beginColumn |-> 1,
                   endLine |-> 16,
                   endColumn |-> 22,
                   module |-> "MCYoYoNoPruning" ] ],
           << 14,
              [ phase |-> <<"up", "down", "down", "up", "up">>,
                incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
                outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
                mailbox |->
                    << {},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]},
                       { [phase |-> "down", val |-> 1, sndr |-> 4],
                         [phase |-> "down", val |-> 1, sndr |-> 5] },
                       {[phase |-> "down", val |-> 1, sndr |-> 5]},
                       {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> >> },
  state |->
      { << 1,
           [ phase |-> <<"down", "down", "down", "down", "down">>,
             incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
             mailbox |-> <<{}, {}, {}, {}, {}>> ] >>,
        << 2,
           [ phase |-> <<"down", "down", "up", "down", "down">>,
             incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
             mailbox |->
                 << {},
                    {},
                    {},
                    {[phase |-> "down", val |-> 3, sndr |-> 3]},
                    {[phase |-> "down", val |-> 3, sndr |-> 3]} >> ] >>,
        << 3,
           [ phase |-> <<"down", "down", "up", "up", "down">>,
             incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
             mailbox |->
                 << {},
                    {},
                    {},
                    {[phase |-> "down", val |-> 3, sndr |-> 3]},
                    { [phase |-> "down", val |-> 3, sndr |-> 3],
                      [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
        << 4,
           [ phase |-> <<"up", "down", "up", "up", "down">>,
             incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    {},
                    {[phase |-> "down", val |-> 3, sndr |-> 3]},
                    { [phase |-> "down", val |-> 1, sndr |-> 1],
                      [phase |-> "down", val |-> 3, sndr |-> 3],
                      [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
        << 5,
           [ phase |-> <<"up", "up", "up", "up", "down">>,
             incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    {},
                    {[phase |-> "down", val |-> 3, sndr |-> 3]},
                    { [phase |-> "down", val |-> 1, sndr |-> 1],
                      [phase |-> "down", val |-> 3, sndr |-> 3],
                      [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
        << 6,
           [ phase |-> <<"up", "down", "up", "up", "down">>,
             incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
             mailbox |->
                 << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                    {},
                    {},
                    {[phase |-> "down", val |-> 3, sndr |-> 3]},
                    { [phase |-> "down", val |-> 1, sndr |-> 1],
                      [phase |-> "down", val |-> 3, sndr |-> 3],
                      [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
        << 7,
           [ phase |-> <<"up", "down", "up", "up", "up">>,
             incoming |-> <<{}, {1}, {}, {3}, {1, 3, 4}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {}>>,
             mailbox |->
                 << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                    {},
                    {},
                    {[phase |-> "down", val |-> 3, sndr |-> 3]},
                    { [phase |-> "down", val |-> 1, sndr |-> 1],
                      [phase |-> "down", val |-> 3, sndr |-> 3],
                      [phase |-> "down", val |-> 3, sndr |-> 4] } >> ] >>,
        << 8,
           [ phase |-> <<"up", "down", "up", "up", "down">>,
             incoming |-> <<{}, {1}, {}, {3}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {5}, {3, 4}>>,
             mailbox |->
                 << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                      [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                    {},
                    {[phase |-> "up", sndr |-> 5, reply |-> "no"]},
                    { [phase |-> "down", val |-> 3, sndr |-> 3],
                      [phase |-> "up", sndr |-> 5, reply |-> "no"] },
                    {} >> ] >>,
        << 9,
           [ phase |-> <<"up", "down", "up", "down", "down">>,
             incoming |-> <<{}, {1}, {}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {4, 5}, {3}, {3, 4}>>,
             mailbox |->
                 << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                      [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                    {},
                    { [phase |-> "up", sndr |-> 4, reply |-> "no"],
                      [phase |-> "up", sndr |-> 5, reply |-> "no"] },
                    {},
                    {} >> ] >>,
        << 10,
           [ phase |-> <<"up", "down", "down", "down", "down">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                      [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                    {},
                    {},
                    {},
                    {} >> ] >>,
        << 11,
           [ phase |-> <<"down", "down", "down", "down", "down">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |-> <<{}, {}, {}, {}, {}>> ] >>,
        << 12,
           [ phase |-> <<"up", "down", "down", "down", "down">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    {},
                    {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
        << 13,
           [ phase |-> <<"up", "down", "down", "down", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
        << 14,
           [ phase |-> <<"up", "down", "down", "up", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    { [phase |-> "down", val |-> 1, sndr |-> 4],
                      [phase |-> "down", val |-> 1, sndr |-> 5] },
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
        << 15,
           [ phase |-> <<"up", "down", "up", "up", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    { [phase |-> "down", val |-> 1, sndr |-> 4],
                      [phase |-> "down", val |-> 1, sndr |-> 5] },
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
        << 16,
           [ phase |-> <<"up", "up", "up", "up", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    { [phase |-> "down", val |-> 1, sndr |-> 4],
                      [phase |-> "down", val |-> 1, sndr |-> 5] },
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
        << 17,
           [ phase |-> <<"up", "down", "up", "up", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                    {},
                    { [phase |-> "down", val |-> 1, sndr |-> 4],
                      [phase |-> "down", val |-> 1, sndr |-> 5] },
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
        << 18,
           [ phase |-> <<"up", "down", "down", "up", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                    {},
                    {},
                    { [phase |-> "down", val |-> 1, sndr |-> 5],
                      [phase |-> "up", sndr |-> 3, reply |-> "yes"] },
                    { [phase |-> "down", val |-> 1, sndr |-> 1],
                      [phase |-> "up", sndr |-> 3, reply |-> "yes"] } >> ] >>,
        << 19,
           [ phase |-> <<"up", "down", "down", "down", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {[phase |-> "up", sndr |-> 2, reply |-> "yes"]},
                    {},
                    {},
                    {},
                    { [phase |-> "down", val |-> 1, sndr |-> 1],
                      [phase |-> "up", sndr |-> 3, reply |-> "yes"],
                      [phase |-> "up", sndr |-> 4, reply |-> "yes"] } >> ] >>,
        << 20,
           [ phase |-> <<"up", "down", "down", "down", "down">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << { [phase |-> "up", sndr |-> 2, reply |-> "yes"],
                      [phase |-> "up", sndr |-> 5, reply |-> "yes"] },
                    {},
                    {},
                    {},
                    {} >> ] >>,
        << 21,
           [ phase |-> <<"down", "down", "down", "down", "down">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |-> <<{}, {}, {}, {}, {}>> ] >>,
        << 22,
           [ phase |-> <<"up", "down", "down", "down", "down">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    {},
                    {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >>,
        << 23,
           [ phase |-> <<"up", "down", "down", "down", "up">>,
             incoming |-> <<{}, {1}, {4, 5}, {5}, {1}>>,
             outgoing |-> <<{2, 5}, {}, {}, {3}, {3, 4}>>,
             mailbox |->
                 << {},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]},
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 5]},
                    {[phase |-> "down", val |-> 1, sndr |-> 1]} >> ] >> } ]

==============================================================================